apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "264Mi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
      app: mongo
  ports:
    - port: 27017
      protocol: TCP
