version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
     volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    image: khushpardhi/backend:latest
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    image: khushpardhi/frontend:latest
    env_file:
      - ./backend/.env.sample
    volumes:
      - ./var/log:/frontend/logs
    ports:
      - "5173:5173"
volumes:
  frontend-logs:
    driver: local
