---
- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'


- name: Ensure directory exists for Docker Compose
  file:
    path: /home/ncs/khush/wanderlust
    state: directory

- name: Stop services using Docker Compose
  command: 
    cmd: docker-compose down
    chdir: /home/ncs/khush/wanderlust
     # become: true

- name: Start services using Docker Compose
  command: 
    cmd: docker-compose up -d
    chdir: /home/ncs/khush/wanderlust