name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull Docker Images to DockerHub
        run: |
          IMAGES=(
            "khushpardhi/backend:Imagetag"
            "khushpardhi/frontend:Imagetag"
          )
          for IMAGE in "${IMAGES[@]}"; do
            echo "Tagging and pushing image: $IMAGE"
            docker pull "$IMAGE"
          done

      - name: Deploy to Server (example step)
        run: |
           docker-compose up -d
