name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull Docker Images to DockerHub
        run: |
          IMAGES=(
            "khushpardhi/backend:Imagetag"
            "khushpardhi/frontend:Imagetag"
          )
          for IMAGE in "${IMAGES[@]}"; do
            echo "Tagging and pushing image: $IMAGE"
            docker pull "$IMAGE"
          done
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures this runs after the build job
    steps:
      - name: Checkout code again for deployment
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx for deployment
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub for deployment
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy Docker Images to Server (SSH Example)
        run: |
          echo "Deploying Docker images to remote server"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Pull the latest images from DockerHub
            docker pull khushpardhi/backend:Imagetag
            docker pull khushpardhi/frontend:Imagetag
            
            # Restart or start services using Docker Compose (modify path as needed)
            cd /path/to/your/docker-compose/project
            docker-compose down
            docker-compose up -d
          EOF
          
