
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: khushpardhi
          password: KHush##@@123
       - name: Build Docker Images with Docker Compose

       steps:
         run: |
          docker-compose build --build-arg IMAGE_TAG=${{ github.event.inputs.imagetag }}

  push-docker-images:
    runs-on: ubuntu-latest
    needs: build-docker-images
        


