# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#     inputs:
#       image_version:
#         description: 'Version for the Docker images'
#         required: true
#         default: 'latest'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2  

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Install Docker Compose
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y docker-compose

#       - name: Build Docker Images with Docker Compose
#         run: |
#           docker-compose build

#       - name: Push Docker Images to DockerHub
#         run: |
#           # Use the image version input from the workflow_dispatch
#           IMAGE_VERSION=${{ github.event.inputs.image_version }}

#           IMAGES=(
#             "khushpardhi/backend:${IMAGE_VERSION}"
#             "khushpardhi/frontend:${IMAGE_VERSION}"
#           )

#           for IMAGE in "${IMAGES[@]}"; do
#             echo "Tagging and pushing image: $IMAGE"
#             docker push "$IMAGE"
#           done
