name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: khushpardhi
          password: KHush##@@123

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Images with Docker Compose
        run: |
          docker-compose build

      - name: Push Docker Images to DockerHub
        run: |
          IMAGES=(
            "khushpardhi/backend:Imagetag"
            "khushpardhi/frontend:Imagetag"
          )
          for IMAGE in "${IMAGES[@]}"; do
            echo "Tagging and pushing image: $IMAGE"
            docker push "$IMAGE"
          done
