on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu:latest

  
      - name: Checkout code
        uses: actions/checkout@v2

      -name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username:
         password:

      -name: build images
       run:
          docker-compose -f docker-compose.yml build

      -name: push on dockerhub
       run:
        docker push ${image}
